In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import gmaps
import gmaps.datasets
import matplotlib.pyplot as plt
import scipy.stats as sts

# File to load
file_to_load = "Resources/listings.csv"

# Read file and store into Pandas data frame
abnb_data = pd.read_csv(file_to_load,low_memory=False)
abnb_data.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,109,https://www.airbnb.com/rooms/109,20191205175409,2019-12-06,Amazing bright elegant condo park front *UPGRA...,"*** Unit upgraded with new bamboo flooring, br...","*** Unit upgraded with new bamboo flooring, br...","*** Unit upgraded with new bamboo flooring, br...",none,NaN,...,f,f,strict_14_with_grace_period,t,f,1,1,0,0,0.02
1,344,https://www.airbnb.com/rooms/344,20191205175409,2019-12-06,Family perfect;Pool;Near Studios!,This home is perfect for families; aspiring ch...,"Cheerful & comfortable; near studios, amusemen...",This home is perfect for families; aspiring ch...,none,Quiet-yet-close to all the fun in LA! Hollywoo...,...,t,f,flexible,f,f,1,1,0,0,0.19
2,2708,https://www.airbnb.com/rooms/2708,20191205175409,2019-12-06,Mirrored Mini-Suite with Fireplace - W. Hollywood,Our best memory foam pillows you'll ever sleep...,Flickering fireplace. Blendtec® Designer 625 ...,Our best memory foam pillows you'll ever sleep...,none,We are minutes away from the Mentor Language I...,...,t,f,strict_14_with_grace_period,f,f,2,0,2,0,0.33
3,2732,https://www.airbnb.com/rooms/2732,20191205175409,2019-12-06,Zen Life at the Beach,NaN,This is a three story townhouse with the follo...,This is a three story townhouse with the follo...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,2,1,1,0,0.19
4,2864,https://www.airbnb.com/rooms/2864,20191205175409,2019-12-07,*Upscale Professional Home with Beautiful Studio*,Centrally located.... Furnished with 42 inch S...,The space is furnished with Thomasville furnit...,Centrally located.... Furnished with 42 inch S...,none,What makes the neighborhood unique is that the...,...,f,f,strict_14_with_grace_period,f,f,1,1,0,0,NaN

In [2]:
# Calculate number of hosts
superhosts = abnb_data.groupby("host_is_superhost")
count = superhosts["id"].nunique()
count.head()
hosts = abnb_data[["id", "host_is_superhost", "latitude", "longitude"]]
hosts.head()

     id host_is_superhost  latitude  longitude
0   109                 f  33.98209 -118.38494
1   344                 f  34.16562 -118.33458
2  2708                 t  34.09768 -118.34602
3  2732                 t  34.00475 -118.48127
4  2864                 f  33.87619 -118.11397

In [3]:
supers_df = hosts.loc[hosts["host_is_superhost"] == "t", :]
supers_df.head()

     id host_is_superhost  latitude  longitude
2  2708                 t  34.09768 -118.34602
3  2732                 t  34.00475 -118.48127
5  5728                 t  33.98833 -118.43224
6  5729                 t  33.98685 -118.43266
7  5843                 t  33.98782 -118.43170

In [4]:
norms_df = hosts.loc[hosts["host_is_superhost"] == "f", :]
norms_df.head()

      id host_is_superhost  latitude  longitude
0    109                 f  33.98209 -118.38494
1    344                 f  34.16562 -118.33458
4   2864                 f  33.87619 -118.11397
8   6033                 f  34.16825 -118.64438
13  8770                 f  33.99399 -118.45637

In [7]:
# Configure gmaps with API key
gmaps.configure(api_key="AIzaSyDznhqYwy3Ml0eN6vAhyaEyBsp-ytvpdQw")

# Store 'Lat' and 'Lng' into  locations 
locations = norms_df[["latitude", "longitude"]].astype(float)

# Handle NaN values
norms_df = norms_df.dropna()
norm_id = norms_df["id"].astype(float)

In [8]:
# Create a Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=norm_id, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
# Create bank symbol layer
final_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
)


fig = gmaps.figure()
fig.add_layer(final_layer)


fig